services:
  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432

  hono-server:
    container_name: ${SERVER_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    ports:
      - ${SERVER_PORT}:8000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres



